config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  root to: 'visitors#index'

  devise_for :users
  resources :companies

  get  'founders/:id', to: 'founders#show', as: 'founder'
  get  'investors', to: 'investors#index'
  get  'investors/:id', to: 'investors#show', as: 'investor'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ratings
end

app/models/company.rb
class Company < ApplicationRecord

  belongs_to :industry
  belongs_to :founder, class_name: "User"
  has_many :investments, class_name: "User"

  validates :name, presence: true

  delegate :name, to: :industry, prefix: true
  delegate :name, to: :founder, prefix: true

end

app/models/concerns/investor.rb
module Investor
  extend ActiveSupport::Concern

  included do

    def overall_rating
      reviews = self.received_reviews.includes(:ratings)
      sum_ratings = reviews.map { |r| r.overall_rating }.reduce(0, :+)
      rating = reviews.size > 0 ? sum_ratings.to_f / reviews.size : sum_ratings
      rating.round(1)
    end

    def latest_reviews
      self.received_reviews.limit(5).order(created_at: :desc)
    end

  end
end

app/models/industry.rb
class Industry < ApplicationRecord
  has_many :companies
end

app/models/investment.rb
class Investment < ApplicationRecord

  belongs_to :investor, class_name: "User"
  belongs_to :company

end

app/models/rating.rb
class Rating < ApplicationRecord

  belongs_to :category
  belongs_to :review

  delegate :name, to: :category, prefix: true

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :founder, class_name: "User"
  belongs_to :investor, class_name: "User"
  has_many :ratings

  delegate :name, :company, to: :founder, prefix: true
  delegate :name, to: :investor, prefix: true

  accepts_nested_attributes_for :ratings, allow_destroy: true

  def overall_rating
    sum_ratings = ratings.pluck(:rate).reduce(0, :+)
    ratings.size > 0 ? sum_ratings / ratings.size : sum_ratings
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Investor

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "70x70#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :companies, foreign_key: "founder_id"
  has_many :investments
  has_many :given_reviews, class_name: "Review", foreign_key: "founder_id"
  has_many :received_reviews, class_name: "Review", foreign_key: "investor_id"

  enum role: [:founder, :investor]

  after_initialize :set_default_role, :if => :new_record?

  scope :founders, -> { where(role: 'founder') }
  scope :investors, -> { where(role: 'investor') }

  private

  def set_default_role
    self.role ||= :founder
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_up_path_for(resource)
    resource.founder? ? new_company_path : companies_path
  end

  def after_sign_in_path_for(resource)
    if resource.founder?
      return investors_path if resource.companies.any?
      return new_company_path
    else
      return companies_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :location])
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :investment_size, :industry_id, :location, :stage, :founder_id)
    end
end

app/controllers/founders_controller.rb
class FoundersController < ApplicationController

  def show
    @founder = User.find(params[:id])
  end

end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: [:show]

  def index
    @query = User.investors.ransack(params[:q])
    @investors = @query.result(distinct: true)
    @investors = @investors.sort_by { |i| i.overall_rating }.reverse
  end

  def show
    @review = @investor.received_reviews.build
    @review.founder = current_user
    @categories = Category.pluck(:name, :id)
  end

  private

  def set_investor
    @investor = User.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)

    respond_to do |format|
      @review.save
      puts @review.errors.full_messages
      format.html { redirect_to investor_path(@review.investor) }
    end
  end

  private

  def review_params
    params.require(:review).permit(
      :comment, :founder_id, :investor_id,
      ratings_attributes: [:rate, :category_id, :review, :_destroy]
    )
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def rate_range
    [[1, 1], [2, 2], [3, 3], [4, 4] , [5, 5]]
  end

  def reviews_text(count)
    return 'No reviews' if count == 0
    return '1 review' if count == 1
    return "#{count} reviews"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def role_options
    [['Founder', 'founder'], ['Investor', 'investor']]
  end

  def can_edit_company(company)
    current_user.founder? && company.founder.id == current_user.id
  end

  def company_owner?
    current_user.founder? && current_user.companies.any?
  end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :founder_id, value: current_user.id %>
    <%= f.input :name %>
    <%= f.input :investment_size %>
    <%= f.association :industry %>
    <%= f.input :location %>
    <%= f.input :stage %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>
<br />
<br />
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Industry</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= company.industry_name %></td>
        <td><%= company.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="pull-right">
  <%= link_to 'Back', companies_path, class: "btn btn-default" %>
  <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-default" if can_edit_company(@company) %>
</div>

<div class="pd-top-lg">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Company</h3>
    </div>

    <div class="panel-body">
      <div class="row">
        <div class="col-lg-4 col-md-4">
          <p><strong>Name: </strong><%= @company.name %></p>
        </div>
        <div class="col-lg-4 col-md-4">
          <p><strong>Founder: </strong><%= @company.founder_name %></p>
        </div>
        <div class="col-lg-4 col-md-4">
          <p><strong>Industry: </strong><%= @company.industry_name %></p>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col-lg-4 col-md-4">
          <p><strong>Investment size: </strong><%= number_to_currency(@company.investment_size, unit: "$") %></p>
        </div>
        <div class="col-lg-4 col-md-4">
          <p><strong>Location: </strong><%= @company.location %></p>
        </div>
        <div class="col-lg-4 col-md-4">
          <p><strong>Stage: </strong><%= @company.stage %></p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/investors/_rating_fields.html.erb
<div class="row">
  <hr />
  <div class="col-lg-6">
    <%= f.input :rate, as: :select, collection: rate_range, include_blank: false, class: 'form-control' %>
  </div>
  <div class="col-lg-6">
    <%= f.input :category_id, as: :select, collection: @categories, include_blank: false, class: 'form-control' %>
  </div>
  <div class="pull-right pd-right-md">
    <%= f.link_to_remove "Remove this rating", class: 'btn btn-default btn-xs' %>
  </div>
</div>

app/views/investors/_review_form.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#review_modal">
  Review
</button>

<div id="review_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog" role="document">

    <div class="modal-content">
      <%= simple_nested_form_for review do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="gridSystemModalLabel">Review <%= review.investor_name %></h4>
        </div>

        <div class="modal-body">
          <%= f.hidden_field :founder_id, value: current_user.id %>
          <%= f.hidden_field :investor_id, value: review.investor.id %>
          <%= f.input :comment, as: :text, class: "form-control", rows: 3 %>
          <div>
            <%= f.simple_fields_for :ratings %>
          </div>
          <p><%= f.link_to_add "Add Rating", :ratings, class: "btn btn-success btn-xs" %></p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= f.submit 'Submit', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->

  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/investors/_reviews.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Latest Reviews</h3>
  </div>

  <div class="panel-body">
    <% reviews.each do |review| %>
      <div class="row">

        <div class="col-md-4">
          <p><strong><%= review.founder_name %></strong>: <%= review.comment %></p>
          <p><em><%= time_ago_in_words(review.created_at) + ' ago' %></em></p>
        </div>

        <div class="col-md-8">
          <p>
            <strong>Ratings:</strong>
            <% review.ratings.each do |rating| %>
              <span class="label label-info pd-side-sm rating-tag">
                <%= rating.category_name %>:
                <%= rating.rate %>
              </span>
            <% end %>
          </p>
        </div>

      </div>
      <hr />
    <% end %>
  </div>
</div>

app/views/investors/index.html.erb
<div class="row mg-bot-lg">
  <div class="col-sm-4">
    <h1>Investors</h1>
  </div>
  <div class="col-sm-8 pd-top-md">
    <form class="form-inline">
      <%= search_form_for(@query, url: "/investors", method: :get) do |f| %>
        <%= f.search_field :name_or_location_cont, placeholder: 'Search by name or location', class: "form-control search-field" %>
        <%= f.submit 'Search', class: "btn btn-default btn-sm" %>
      <% end %>
    </form>
  </div>
</div>

<table class="table table-hover">
  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= link_to image_tag(investor.avatar.url(:thumb)), investor_path(investor) %></td>

        <td>
          <div class="row investor-info">
            <%= link_to investor.name, investor_path(investor) %>
          </div>
          <div class="row">
            <%= investor.location %>
          </div>
        </td>

        <td>
          <div class="row investor-info">
            <%= investor.overall_rating %>
          </div>
          <div class="row">
            <%= reviews_text(investor.received_reviews.count) %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/investors/show.html.erb
<div class="pull-right">
  <%= render 'review_form', review: @review if current_user.founder? %>
  <%= link_to 'Back', investors_path, class: "btn btn-default" %>
</div>

<div class="pd-top-lg">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Investor</h3>
    </div>

    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <p class="img-circle"><%= image_tag(@investor.avatar.url(:medium)) %></p>
        </div>

        <div class="col-md-4">
          <p><strong>Name: </strong><%= @investor.name %></p>
          <p><strong>Email: </strong><%= @investor.email %></p>
          <p><strong>Location: </strong><%= @investor.location %></p>
        </div>

        <div class="col-md-4">
          <p class="investor-info"><%= @investor.overall_rating %></p>
          <p><%= reviews_text(@investor.received_reviews.count) %></p>
        </div>

      </div>
    </div>
  </div>

  <div>
    <%= render 'reviews', reviews: @investor.latest_reviews %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<p class="mg-top-lg">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</p>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class="navbar-link pd-top-md pd-side-md"> <%= current_user.name %></li>
  <li>
    <div class="dropdown">
      <button class="dropdown-toggle round-image-nav bordered" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= image_tag(current_user.avatar.url(:thumb)) %>
      </button>

      <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
        <li><%= link_to 'My company', company_path(current_user.companies.first) if company_owner? %></li>
        <li><%= link_to 'My profile', investor_path(current_user) if current_user.investor? %></li>
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
      </ul>
    </div>
  </li>


<% else %>
  <li class="navbar-link"><%= link_to 'Sign in', new_user_session_path %></li>
  <li class="navbar-link"><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Glassdollar', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li class="navbar-link"><%= link_to 'Investors', investors_path %></li>
  <li class="navbar-link"><%= link_to 'Companies', companies_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Glassdollar" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Glassdollar" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-sm-12 text-center">
          <h1>Glassdollar</h1>
        </div>
    </div>
    <!-- /.row -->
    <hr />
    <div class="jumbotron">
      <div class="row">
        <dir class="col-md-8">
          <h3>Developed by Camilo Sad</h3>
          <br />
          <h4>Project created as a solution for a challenge proposed during the <a href="http://www.vanhack.com/hackathon/" target="_blank">Vanhackathon</a> event.</h4>
        </dir>
        <div class="col-md-4">
          <img src="https://scontent.fsdu8-1.fna.fbcdn.net/v/t1.0-1/p160x160/15727121_1037686113002566_1636224737058986320_n.jpg?oh=bad23091e897826ec87c9e7ba4715b04&oe=59531F92" class="img-circle">
        </div>
      </div>

      <hr />
      <div class="row">
        <div class="col-lg-8">
          As the challenge description suggests, this is basically a place to read reviews of founders about their investors.
          <br />
          <br />

          In order to make things easier, the database was already set up with a couple of records.
          You can either sign up as a new user or log in using one of the following existing accounts:
          <ul>
            <li>email: founder1@email.com / pass: 123456</li>
            <li>email: investor1@email.com / pass: 123456</li>
          </ul>

          That is an initial idea and it has a lot of space for improvements.
          But if you see this as is a good start and would like to know more about my work, please feel free to contact me any time.
        </div>

        <div class="col-lg-1"></div>

        <div class="col-lg-3">
          <p>
            <ul class="list-unstyled">
              <li class="pd-bot-md pd-left-sm"><strong>sadcamilo@gmail.com</strong></li>
              <li>
                <a class="btn btn-link" href="https://github.com/camilosad" target="_blank">GitHub</a>
              </li>
              <li>
                <a class="btn btn-link" href="https://www.linkedin.com/in/camilosad/" target="_blank">LinkedIn</a>
              </li>
              <li>
                <a class="btn btn-link" href="https://bitbucket.org/camilosad/glassdollar/src" target="_blank">Source code</a>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>


</div>
<!-- /.container -->